#!/bin/sh

set -e

if [[ -z "${CI}" ]]; then
  export TREE_SITTER_PARSER_DIR=$(pwd)/test/tree-sitter/fixtures/parsers
else
  git submodule sync
  git submodule update --init
  bundle
  bundle exec rake clean
fi

bundle exec rake test
